const SUPABASE_URL='https://uoqastprrdlwlsesheoz.supabase.co';
const SUPABASE_KEY='sb_publishable_vCRrqr_Zi1Zg1jN-LOrV3Q_7I0LnzKu';
const STORE='yunaAuth',STATE_URL=SUPABASE_URL+'/rest/v1/yuna_state?id=eq.family';let session=null,installPrompt=null;
// Private Angaben stehen ausschliesslich in Supabase und nicht im öffentlichen GitHub-Code.
const initial={paws:{'Vorne links':'','Vorne rechts':'','Hinten links':'','Hinten rechts':''},heat:'',milk:'',vaccine:'',vaccineName:'',tick:'',tickName:'',tickSpring:'',tickAutumn:'',worming:'',wormingNext:'',barfAmount:'',travelFoodAmount:'',foodTimes:'',vetName:'',vetAddress:'',vetPhone:'',reminder:'',notes:''};let data=structuredClone(initial),lastCloud='';
const $=s=>document.querySelector(s),fmt=d=>d?new Intl.DateTimeFormat('de-CH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00')):'Noch offen';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headers=()=>({'apikey':SUPABASE_KEY,'Authorization':'Bearer '+session.access_token,'Content-Type':'application/json'});
async function signIn(email,password){const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok)throw Error(d.error_description||d.msg||d.message||'Anmeldung fehlgeschlagen');session=d;localStorage.setItem(STORE,JSON.stringify(d))}
async function refresh(){if(!session?.refresh_token)return false;try{const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}),d=await r.json();if(!r.ok)throw Error();session=d;localStorage.setItem(STORE,JSON.stringify(d));return true}catch{return false}}
async function load(){const r=await fetch(STATE_URL+'&select=data',{headers:headers(),cache:'no-store'});if(r.status===401&&await refresh())return load();if(!r.ok)throw Error(await r.text());const rows=await r.json();data={...initial,...(rows[0]?.data||{}),paws:{...initial.paws,...(rows[0]?.data?.paws||{})}};lastCloud=JSON.stringify(data);render()}
async function save(){const body=JSON.stringify({data,updated_at:new Date().toISOString()}),r=await fetch(STATE_URL,{method:'PATCH',headers:{...headers(),Prefer:'return=minimal'},body});if(!r.ok)throw Error(await r.text());lastCloud=JSON.stringify(data);$('#status').classList.remove('hidden');setTimeout(()=>$('#status').classList.add('hidden'),2200)}
function info(icon,title,main,sub){return `<article class="info"><div class="icon">${icon}</div><h3>${title}</h3><p>${esc(sub)}</p><strong>${esc(main)}</strong></article>`}function reminder(title,date){return `<div class="reminder"><b>📅 ${title}</b><span>${fmt(date)}</span></div>`}
function render(){$('#health').innerHTML=info('🛡️','Zeckenschutz',data.tickName||'Noch offen',`Zuletzt: ${fmt(data.tick)} · Nächste Erinnerung: ${fmt(data.tickSpring)}`)+info('💉','Impfung',data.vaccineName||'Noch offen',`Zuletzt: ${fmt(data.vaccine)}`)+info('〰️','Entwurmung',`Nächste: ${fmt(data.wormingNext)}`,`Zuletzt: ${fmt(data.worming)}`)+info('♡','Läufigkeit & Milcheinschuss',fmt(data.heat),data.milk?`Milcheinschuss: ${fmt(data.milk)}`:'Noch kein Milcheinschuss eingetragen');$('#paws').innerHTML=Object.entries(data.paws).map(([p,d])=>`<div class="paw"><span>🐾</span><b>${esc(p)}</b><small>${fmt(d)}</small></div>`).join('');$('#reminders').innerHTML=reminder('Gemäss Tierarzt',data.reminder)+reminder('Zeckenschutz Frühling',data.tickSpring)+reminder('Zeckenschutz Spätsommer',data.tickAutumn);$('#food').innerHTML=`<h3>🦴 Futter</h3><div class="food-block"><span class="pill">Zuhause · BARF</span><strong>2 × ${esc(data.barfAmount||'–')}</strong></div><div class="food-block"><span class="pill">Reise · Nassfutter</span><strong>2 × ${esc(data.travelFoodAmount||'–')}</strong></div><p>Jeweils ${esc(data.foodTimes||'noch offen')}</p>`;$('#vet').innerHTML=`<h3>📍 Tierarzt</h3><b>${esc(data.vetName||'Noch offen')}</b><p>${esc(data.vetAddress)}<br>${esc(data.vetPhone)}</p><a href="tel:${esc(data.vetPhone)}"><button class="outline">Jetzt anrufen</button></a>`;$('#holiday').innerHTML=`<h3>Wichtig in den Ferien</h3><p>${esc(data.notes||'Noch keine Hinweise eingetragen.')}</p>`}
const fields=[['heat','Letzte Läufigkeit','date'],['milk','Milcheinschuss','date'],['vaccine','Letzte Impfung','date'],['vaccineName','Impfung / Präparat'],['tick','Letzter Zeckenschutz','date'],['tickName','Zeckenmittel'],['tickSpring','Zecken-Erinnerung Frühling','date'],['tickAutumn','Zecken-Erinnerung Spätsommer','date'],['worming','Letzte Entwurmung','date'],['wormingNext','Nächste Entwurmung laut Produkt','date'],['reminder','Nächster Termin gemäss Tierarzt','date'],['barfAmount','BARF pro Mahlzeit'],['travelFoodAmount','Nassfutter auf Reisen pro Mahlzeit'],['foodTimes','Futterzeiten'],['vetName','Tierarzt'],['vetPhone','Telefon'],['vetAddress','Adresse'],['notes','Ferienhinweise','textarea']];
function openEditor(){const pawFields=Object.entries(data.paws).map(([key,value])=>`<label>${esc(key)} geschliffen<input data-paw="${esc(key)}" type="date" value="${esc(value)}"></label>`).join('');$('#fields').innerHTML=pawFields+fields.map(([key,label,type='text'])=>`<label>${label}${type==='textarea'?`<textarea data-key="${key}">${esc(data[key]||'')}</textarea>`:`<input data-key="${key}" type="${type}" value="${esc(data[key]||'')}">`}</label>`).join('');$('#editor').showModal()}
$('#editForm').onsubmit=async e=>{e.preventDefault();document.querySelectorAll('[data-key]').forEach(x=>data[x.dataset.key]=x.value);document.querySelectorAll('[data-paw]').forEach(x=>data.paws[x.dataset.paw]=x.value);await save();render();$('#editor').close()};$('#editBtn').onclick=openEditor;$('#closeBtn').onclick=$('#cancelBtn').onclick=()=>$('#editor').close();
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await signIn($('#email').value.trim(),$('#password').value);$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load()}catch(x){$('#loginError').textContent=x.message==='Invalid login credentials'?'E-Mail oder Passwort stimmt nicht.':x.message}};$('#logoutBtn').onclick=()=>{localStorage.removeItem(STORE);session=null;$('#app').classList.add('hidden');$('#login').classList.remove('hidden')};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('#installBtn').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else alert('iPhone/iPad: In Safari auf „Teilen“ und dann „Zum Home-Bildschirm“ tippen.')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
(async()=>{try{session=JSON.parse(localStorage.getItem(STORE)||'null')}catch{}if(session&&await refresh()){$('#login').classList.add('hidden');$('#app').classList.remove('hidden');await load()}else localStorage.removeItem(STORE)})();setInterval(async()=>{if(!session||document.hidden)return;try{const r=await fetch(STATE_URL+'&select=data',{headers:headers(),cache:'no-store'}),rows=await r.json(),next=JSON.stringify(rows[0]?.data||{});if(rows[0]?.data&&next!==lastCloud){data={...initial,...rows[0].data};lastCloud=next;render()}}catch{}},3000);

